# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_directory/GUI/client_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1293, 995)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(45, 45, 45);\n"
"background-color: rgb(0, 0, 0);\n"
"background-color: rgb(24, 24, 36);\n"
"background-color: #1f232a;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: #16191d;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(45, 45, 45);\n"
"background-color: rgb(9, 5, 13)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_minimize_window = QtWidgets.QPushButton(self.frame_4)
        self.btn_minimize_window.setStyleSheet("QPushButton {\n"
"     background-color: #16191d;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2c313c;\n"
"}\n"
"\n"
"")
        self.btn_minimize_window.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons_2/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize_window.setIcon(icon)
        self.btn_minimize_window.setIconSize(QtCore.QSize(25, 25))
        self.btn_minimize_window.setObjectName("btn_minimize_window")
        self.horizontalLayout_2.addWidget(self.btn_minimize_window)
        self.btn_restore_window = QtWidgets.QPushButton(self.frame_4)
        self.btn_restore_window.setStyleSheet("QPushButton {\n"
"     background-color: #16191d;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2c313c;\n"
"}\n"
"\n"
"")
        self.btn_restore_window.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons_2/maximize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_restore_window.setIcon(icon1)
        self.btn_restore_window.setIconSize(QtCore.QSize(25, 25))
        self.btn_restore_window.setObjectName("btn_restore_window")
        self.horizontalLayout_2.addWidget(self.btn_restore_window)
        self.btn_close_window = QtWidgets.QPushButton(self.frame_4)
        self.btn_close_window.setStyleSheet("QPushButton {\n"
"     background-color: #16191d;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2c313c;\n"
"}\n"
"\n"
"")
        self.btn_close_window.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons_2/x-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close_window.setIcon(icon2)
        self.btn_close_window.setIconSize(QtCore.QSize(25, 25))
        self.btn_close_window.setObjectName("btn_close_window")
        self.horizontalLayout_2.addWidget(self.btn_close_window)
        self.horizontalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.authorization_page = QtWidgets.QWidget()
        self.authorization_page.setStyleSheet("background-color: #16191d;\n"
"")
        self.authorization_page.setObjectName("authorization_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.authorization_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.authorization_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_30.setSpacing(20)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(140, 40))
        self.label_2.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_30.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.le_login = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_login.sizePolicy().hasHeightForWidth())
        self.le_login.setSizePolicy(sizePolicy)
        self.le_login.setMinimumSize(QtCore.QSize(0, 40))
        self.le_login.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.le_login.setFont(font)
        self.le_login.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_login.setObjectName("le_login")
        self.verticalLayout_30.addWidget(self.le_login)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setMinimumSize(QtCore.QSize(140, 0))
        self.label_3.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_30.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.le_password = QtWidgets.QLineEdit(self.frame_5)
        self.le_password.setMinimumSize(QtCore.QSize(0, 40))
        self.le_password.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.le_password.setFont(font)
        self.le_password.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_password.setObjectName("le_password")
        self.verticalLayout_30.addWidget(self.le_password)
        self.btn_login = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_login.sizePolicy().hasHeightForWidth())
        self.btn_login.setSizePolicy(sizePolicy)
        self.btn_login.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_login.setMaximumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid rgb(24, 24, 36);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_login.setFlat(False)
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout_30.addWidget(self.btn_login)
        self.verticalLayout_3.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.authorization_page)
        self.two_factor_authentication_page = QtWidgets.QWidget()
        self.two_factor_authentication_page.setStyleSheet("background-color: #16191d;\n"
"")
        self.two_factor_authentication_page.setObjectName("two_factor_authentication_page")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.two_factor_authentication_page)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.frame_33 = QtWidgets.QFrame(self.two_factor_authentication_page)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_44.setContentsMargins(20, 20, -1, 20)
        self.verticalLayout_44.setSpacing(20)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.label_21 = QtWidgets.QLabel(self.frame_33)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_44.addWidget(self.label_21)
        self.le_email_code = QtWidgets.QLineEdit(self.frame_33)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.le_email_code.setFont(font)
        self.le_email_code.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_email_code.setObjectName("le_email_code")
        self.verticalLayout_44.addWidget(self.le_email_code)
        self.btn_accept_code = QtWidgets.QPushButton(self.frame_33)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_accept_code.setFont(font)
        self.btn_accept_code.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid rgb(24, 24, 36);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_accept_code.setObjectName("btn_accept_code")
        self.verticalLayout_44.addWidget(self.btn_accept_code)
        self.btn_open_authorization_page = QtWidgets.QPushButton(self.frame_33)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_authorization_page.setFont(font)
        self.btn_open_authorization_page.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid rgb(24, 24, 36);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_open_authorization_page.setObjectName("btn_open_authorization_page")
        self.verticalLayout_44.addWidget(self.btn_open_authorization_page)
        self.verticalLayout_43.addWidget(self.frame_33, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.two_factor_authentication_page)
        self.main_container_page = QtWidgets.QWidget()
        self.main_container_page.setObjectName("main_container_page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.main_container_page)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.menu_container = QtWidgets.QFrame(self.main_container_page)
        self.menu_container.setMaximumSize(QtCore.QSize(320, 16777215))
        self.menu_container.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"background-color: #16191d;")
        self.menu_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_container.setObjectName("menu_container")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.menu_container)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.menu_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toolBox = QtWidgets.QToolBox(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #16191d;")
        self.toolBox.setObjectName("toolBox")
        self.page_dbms_menu = QtWidgets.QWidget()
        self.page_dbms_menu.setGeometry(QtCore.QRect(0, 0, 278, 675))
        self.page_dbms_menu.setObjectName("page_dbms_menu")
        self.splitter_3 = QtWidgets.QSplitter(self.page_dbms_menu)
        self.splitter_3.setGeometry(QtCore.QRect(10, 130, 251, 271))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.btn_dbms_manual = QtWidgets.QPushButton(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dbms_manual.setFont(font)
        self.btn_dbms_manual.setStyleSheet("QPushButton {\n"
"    border: 5px groove #2c313c;\n"
"    border-left-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: #16191d;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2c313c;\n"
"    border: 5px solid  rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.btn_dbms_manual.setObjectName("btn_dbms_manual")
        self.btn_open_list_of_db = QtWidgets.QPushButton(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_list_of_db.setFont(font)
        self.btn_open_list_of_db.setStyleSheet("QPushButton {\n"
"    border: 5px groove #2c313c;\n"
"    border-left-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: #16191d;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2c313c;\n"
"    border: 5px solid  rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.btn_open_list_of_db.setObjectName("btn_open_list_of_db")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons_2/database.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_dbms_menu, icon3, "")
        self.horizontalLayout_6.addWidget(self.toolBox)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.menu_container)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_main_page_manual = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_main_page_manual.setFont(font)
        self.btn_main_page_manual.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid rgb(24, 24, 36);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons_2/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_main_page_manual.setIcon(icon4)
        self.btn_main_page_manual.setObjectName("btn_main_page_manual")
        self.verticalLayout_5.addWidget(self.btn_main_page_manual)
        self.btn_open_license = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_license.setFont(font)
        self.btn_open_license.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid rgb(24, 24, 36);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/icons_2/layers.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_open_license.setIcon(icon5)
        self.btn_open_license.setObjectName("btn_open_license")
        self.verticalLayout_5.addWidget(self.btn_open_license)
        self.btn_open_authorization_page_2 = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_authorization_page_2.setFont(font)
        self.btn_open_authorization_page_2.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid rgb(24, 24, 36);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/icons_2/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_open_authorization_page_2.setIcon(icon6)
        self.btn_open_authorization_page_2.setObjectName("btn_open_authorization_page_2")
        self.verticalLayout_5.addWidget(self.btn_open_authorization_page_2)
        self.btn_exit = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid rgb(24, 24, 36);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_exit.setIcon(icon2)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout_5.addWidget(self.btn_exit)
        self.verticalLayout_4.addWidget(self.frame_9, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_5.addWidget(self.menu_container)
        self.frame_7 = QtWidgets.QFrame(self.main_container_page)
        self.frame_7.setStyleSheet("background-color: #2c313c;\n"
"background-color: #1f232a;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stackedWidget_main = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget_main.setObjectName("stackedWidget_main")
        self.page_about_system = QtWidgets.QWidget()
        self.page_about_system.setObjectName("page_about_system")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_about_system)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_6 = QtWidgets.QFrame(self.page_about_system)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.verticalLayout_7.addWidget(self.frame_6, 0, QtCore.Qt.AlignTop)
        self.frame_10 = QtWidgets.QFrame(self.page_about_system)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.textEdit = QtWidgets.QTextEdit(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    border: 5px groove #2c313c;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_9.addWidget(self.textEdit)
        self.verticalLayout_7.addWidget(self.frame_10)
        self.stackedWidget_main.addWidget(self.page_about_system)
        self.page_license = QtWidgets.QWidget()
        self.page_license.setObjectName("page_license")
        self.verticalLayout_58 = QtWidgets.QVBoxLayout(self.page_license)
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.frame_42 = QtWidgets.QFrame(self.page_license)
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.verticalLayout_59 = QtWidgets.QVBoxLayout(self.frame_42)
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.frame_43 = QtWidgets.QFrame(self.frame_42)
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.verticalLayout_60 = QtWidgets.QVBoxLayout(self.frame_43)
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.label_43 = QtWidgets.QLabel(self.frame_43)
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 16777207))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_60.addWidget(self.label_43, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_59.addWidget(self.frame_43, 0, QtCore.Qt.AlignTop)
        self.frame_44 = QtWidgets.QFrame(self.frame_42)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_44.sizePolicy().hasHeightForWidth())
        self.frame_44.setSizePolicy(sizePolicy)
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout(self.frame_44)
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.textEdit_7 = QtWidgets.QTextEdit(self.frame_44)
        self.textEdit_7.setStyleSheet("QTextEdit {\n"
"    border: 5px groove #2c313c;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.textEdit_7.setObjectName("textEdit_7")
        self.verticalLayout_61.addWidget(self.textEdit_7)
        self.verticalLayout_59.addWidget(self.frame_44)
        self.verticalLayout_58.addWidget(self.frame_42)
        self.stackedWidget_main.addWidget(self.page_license)
        self.page_dbms_manual = QtWidgets.QWidget()
        self.page_dbms_manual.setObjectName("page_dbms_manual")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.page_dbms_manual)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_22 = QtWidgets.QFrame(self.page_dbms_manual)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.label_41 = QtWidgets.QLabel(self.frame_22)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_47.addWidget(self.label_41)
        self.textEdit_4 = QtWidgets.QTextEdit(self.frame_22)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setStyleSheet("QTextEdit {\n"
"    border: 5px groove #2c313c;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.textEdit_4.setReadOnly(True)
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout_47.addWidget(self.textEdit_4)
        self.verticalLayout_26.addWidget(self.frame_22)
        self.stackedWidget_main.addWidget(self.page_dbms_manual)
        self.page_show_dbms = QtWidgets.QWidget()
        self.page_show_dbms.setObjectName("page_show_dbms")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.page_show_dbms)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.frame_27 = QtWidgets.QFrame(self.page_show_dbms)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_39 = QtWidgets.QLabel(self.frame_27)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_36.addWidget(self.label_39)
        self.tabWidget = QtWidgets.QTabWidget(self.frame_27)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_add_data = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tab_add_data.setFont(font)
        self.tab_add_data.setObjectName("tab_add_data")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.tab_add_data)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 0, -1, -1)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.tab_add_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.le_name = QtWidgets.QLineEdit(self.tab_add_data)
        self.le_name.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.le_name.setFont(font)
        self.le_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_name.setObjectName("le_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_name)
        self.label_7 = QtWidgets.QLabel(self.tab_add_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.le_soname = QtWidgets.QLineEdit(self.tab_add_data)
        self.le_soname.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.le_soname.setFont(font)
        self.le_soname.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_soname.setObjectName("le_soname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_soname)
        self.label_8 = QtWidgets.QLabel(self.tab_add_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.le_position = QtWidgets.QLineEdit(self.tab_add_data)
        self.le_position.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.le_position.setFont(font)
        self.le_position.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_position.setObjectName("le_position")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_position)
        self.label_9 = QtWidgets.QLabel(self.tab_add_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.le_email = QtWidgets.QLineEdit(self.tab_add_data)
        self.le_email.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.le_email.setFont(font)
        self.le_email.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_email.setObjectName("le_email")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_email)
        self.label_10 = QtWidgets.QLabel(self.tab_add_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.le_login_2 = QtWidgets.QLineEdit(self.tab_add_data)
        self.le_login_2.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.le_login_2.setFont(font)
        self.le_login_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_login_2.setObjectName("le_login_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.le_login_2)
        self.label_11 = QtWidgets.QLabel(self.tab_add_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.le_password_2 = QtWidgets.QLineEdit(self.tab_add_data)
        self.le_password_2.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.le_password_2.setFont(font)
        self.le_password_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_password_2.setObjectName("le_password_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.le_password_2)
        self.label_12 = QtWidgets.QLabel(self.tab_add_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cb_user_role = QtWidgets.QComboBox(self.tab_add_data)
        self.cb_user_role.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.cb_user_role.setFont(font)
        self.cb_user_role.setStyleSheet("color: rgb(255, 255, 255);")
        self.cb_user_role.setObjectName("cb_user_role")
        self.cb_user_role.addItem("")
        self.cb_user_role.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cb_user_role)
        self.btn_add_new_user = QtWidgets.QPushButton(self.tab_add_data)
        self.btn_add_new_user.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add_new_user.setFont(font)
        self.btn_add_new_user.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid #1f232a;;\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_add_new_user.setObjectName("btn_add_new_user")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.btn_add_new_user)
        self.verticalLayout_29.addLayout(self.formLayout)
        self.tabWidget.addTab(self.tab_add_data, "")
        self.tab_data = QtWidgets.QWidget()
        self.tab_data.setObjectName("tab_data")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.tab_data)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.data_table_view = QtWidgets.QTableView(self.tab_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.data_table_view.setFont(font)
        self.data_table_view.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.data_table_view.setObjectName("data_table_view")
        self.verticalLayout_42.addWidget(self.data_table_view)
        self.tabWidget.addTab(self.tab_data, "")
        self.tab_search_page = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tab_search_page.setFont(font)
        self.tab_search_page.setObjectName("tab_search_page")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.tab_search_page)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.le_search_data_in_db = QtWidgets.QLineEdit(self.tab_search_page)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.le_search_data_in_db.setFont(font)
        self.le_search_data_in_db.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_search_data_in_db.setObjectName("le_search_data_in_db")
        self.verticalLayout_27.addWidget(self.le_search_data_in_db)
        self.search_table_view = QtWidgets.QTableView(self.tab_search_page)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.search_table_view.setFont(font)
        self.search_table_view.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.search_table_view.setObjectName("search_table_view")
        self.verticalLayout_27.addWidget(self.search_table_view)
        self.tabWidget.addTab(self.tab_search_page, "")
        self.tab_change_page = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tab_change_page.setFont(font)
        self.tab_change_page.setObjectName("tab_change_page")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.tab_change_page)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.change_table_view = QtWidgets.QTableView(self.tab_change_page)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.change_table_view.setFont(font)
        self.change_table_view.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.change_table_view.setObjectName("change_table_view")
        self.verticalLayout_28.addWidget(self.change_table_view)
        self.tabWidget.addTab(self.tab_change_page, "")
        self.tab_delete_page = QtWidgets.QWidget()
        self.tab_delete_page.setObjectName("tab_delete_page")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.tab_delete_page)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.delete_table_view = QtWidgets.QTableView(self.tab_delete_page)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.delete_table_view.setFont(font)
        self.delete_table_view.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delete_table_view.setObjectName("delete_table_view")
        self.verticalLayout_31.addWidget(self.delete_table_view)
        self.tabWidget.addTab(self.tab_delete_page, "")
        self.verticalLayout_36.addWidget(self.tabWidget)
        self.verticalLayout_25.addWidget(self.frame_27)
        self.stackedWidget_main.addWidget(self.page_show_dbms)
        self.page_list_of_db = QtWidgets.QWidget()
        self.page_list_of_db.setObjectName("page_list_of_db")
        self.verticalLayout_52 = QtWidgets.QVBoxLayout(self.page_list_of_db)
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.label_38 = QtWidgets.QLabel(self.page_list_of_db)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_52.addWidget(self.label_38)
        self.frame_37 = QtWidgets.QFrame(self.page_list_of_db)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_37.sizePolicy().hasHeightForWidth())
        self.frame_37.setSizePolicy(sizePolicy)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.verticalLayout_53 = QtWidgets.QVBoxLayout(self.frame_37)
        self.verticalLayout_53.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.frame_38 = QtWidgets.QFrame(self.frame_37)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_38.sizePolicy().hasHeightForWidth())
        self.frame_38.setSizePolicy(sizePolicy)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_38)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_40 = QtWidgets.QFrame(self.frame_38)
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.verticalLayout_56 = QtWidgets.QVBoxLayout(self.frame_40)
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.label_29 = QtWidgets.QLabel(self.frame_40)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_29.setObjectName("label_29")
        self.verticalLayout_56.addWidget(self.label_29)
        self.lw_db_widget = QtWidgets.QListWidget(self.frame_40)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lw_db_widget.setFont(font)
        self.lw_db_widget.setStyleSheet("QListWidget {\n"
"    border: 5px groove #2c313c;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.lw_db_widget.setObjectName("lw_db_widget")
        self.verticalLayout_56.addWidget(self.lw_db_widget)
        self.horizontalLayout_11.addWidget(self.frame_40)
        self.frame_41 = QtWidgets.QFrame(self.frame_38)
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.verticalLayout_55 = QtWidgets.QVBoxLayout(self.frame_41)
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.label_30 = QtWidgets.QLabel(self.frame_41)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_30.setObjectName("label_30")
        self.verticalLayout_55.addWidget(self.label_30)
        self.lw_table_widget = QtWidgets.QListWidget(self.frame_41)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lw_table_widget.setFont(font)
        self.lw_table_widget.setStyleSheet("QListWidget {\n"
"    border: 5px groove #2c313c;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.lw_table_widget.setObjectName("lw_table_widget")
        self.verticalLayout_55.addWidget(self.lw_table_widget)
        self.horizontalLayout_11.addWidget(self.frame_41)
        self.verticalLayout_53.addWidget(self.frame_38, 0, QtCore.Qt.AlignTop)
        self.frame_39 = QtWidgets.QFrame(self.frame_37)
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_54 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.tv_for_db_view = QtWidgets.QTableView(self.frame_39)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tv_for_db_view.setFont(font)
        self.tv_for_db_view.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tv_for_db_view.setObjectName("tv_for_db_view")
        self.verticalLayout_54.addWidget(self.tv_for_db_view)
        self.verticalLayout_53.addWidget(self.frame_39)
        self.verticalLayout_52.addWidget(self.frame_37)
        self.stackedWidget_main.addWidget(self.page_list_of_db)
        self.verticalLayout_6.addWidget(self.stackedWidget_main)
        self.size_grip = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.size_grip.sizePolicy().hasHeightForWidth())
        self.size_grip.setSizePolicy(sizePolicy)
        self.size_grip.setMaximumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.size_grip.setFont(font)
        self.size_grip.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.size_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.size_grip.setObjectName("size_grip")
        self.verticalLayout_57 = QtWidgets.QVBoxLayout(self.size_grip)
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.pushButton = QtWidgets.QPushButton(self.size_grip)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_57.addWidget(self.pushButton, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout_6.addWidget(self.size_grip, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout_5.addWidget(self.frame_7)
        self.stackedWidget.addWidget(self.main_container_page)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.toolBox.setCurrentIndex(0)
        self.stackedWidget_main.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Клиент"))
        self.label_2.setText(_translate("MainWindow", "ЛОГИН"))
        self.label_3.setText(_translate("MainWindow", "ПАРОЛЬ"))
        self.btn_login.setText(_translate("MainWindow", "Войти"))
        self.label_21.setText(_translate("MainWindow", "Код подтверждения"))
        self.btn_accept_code.setText(_translate("MainWindow", "Подтвердить"))
        self.btn_open_authorization_page.setText(_translate("MainWindow", "Страница авторизации"))
        self.btn_dbms_manual.setText(_translate("MainWindow", "Руководство\n"
"пользователя"))
        self.btn_open_list_of_db.setText(_translate("MainWindow", "Список баз данных"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_dbms_menu), _translate("MainWindow", "Базы данных"))
        self.btn_main_page_manual.setText(_translate("MainWindow", "Главная страница"))
        self.btn_open_license.setText(_translate("MainWindow", "Лицензия"))
        self.btn_open_authorization_page_2.setText(_translate("MainWindow", "Страница авторизации"))
        self.btn_exit.setText(_translate("MainWindow", "Выход"))
        self.label_4.setText(_translate("MainWindow", "Информация о клиенте"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Клиент.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Специальное программное обеспечение, которое предназначено для пользователей. При помощи данного программного обеспечения пользователи делают запрос к базе данных и получают необходимую им информацию.</span></p></body></html>"))
        self.label_43.setText(_translate("MainWindow", "Лицензия"))
        self.textEdit_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Действующая лицензия - Apache License 2.0</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Срок действия - бессрочная </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Авторское право (c) 2022 Макеев Антон Николаевич</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">ПРАВИЛА И УСЛОВИЯ ИСПОЛЬЗОВАНИЯ, ВОСПРОИЗВЕДЕНИЯ И РАСПРОСТРАНЕНИЯ</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Определения.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">&quot;Лицензия&quot; означает условия использования, воспроизведения и распространения, определенные разделами 1-9 настоящего документа.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">&quot;Лицензиар&quot; означает владельца авторских прав или юридическое лицо, уполномоченное владельцем авторских прав, которое предоставляет Лицензию.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">&quot;Юридическое лицо&quot; означает объединение действующего юридического лица и всех других юридических лиц, которые контролируют, контролируются или находятся под общим контролем с этим юридическим лицом. Для целей настоящего определения &quot;контроль&quot; означает (i) право, прямое или косвенное, осуществлять руководство или управление такой организацией, будь то по контракту или иным образом, или (ii) владение пятьюдесятью процентами (50%) или более размещенных акций, или (iii) бенефициарное владение такой организацией.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">&quot;Вы&quot; (или &quot;Ваш&quot;) означает физическое или юридическое лицо, осуществляющее разрешения, предоставленные настоящей Лицензией.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">&quot;Исходная&quot; форма означает предпочтительную форму для внесения изменений, включая, но не ограничиваясь, исходный код программного обеспечения, исходный код документации и файлы конфигурации.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">&quot;Объектная&quot; форма означает любую форму, полученную в результате механического преобразования или перевода Исходной формы, включая, но не ограничиваясь этим, скомпилированный объектный код, сгенерированную документацию и преобразования в другие типы носителей.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">&quot;Произведение&quot; означает авторское произведение, будь то в форме Источника или Объекта, доступное по Лицензии, как указано в уведомлении об авторских правах, которое включено в произведение или прилагается к нему (пример приведен в Приложении ниже).</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">&quot;Производные работы&quot; означают любую работу, будь то в форме Источника или Объекта, которая основана на (или получена из) Работы и для которой редакторские правки, аннотации, уточнения или другие модификации представляют в целом оригинальное авторское произведение. Для целей настоящей Лицензии Производные произведения не должны включать произведения, которые остаются отделимыми от Произведения и Производных от него Произведений или просто ссылаются (или привязываются по названию) на интерфейсы Произведения и Производных от него Произведений.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">&quot;Вклад&quot; означает любое авторское произведение, включая оригинальную версию Произведения и любые изменения или дополнения к этому Произведению или Производные от него Произведения, которые намеренно представлены Лицензиару для включения в Произведение владельцем авторских прав или физическим или юридическим лицом, уполномоченным представлять от имени владельца авторских прав владелец. Для целей этого определения &quot;отправлено&quot; означает любую форму электронного, устного или письменного сообщения, отправленного Лицензиару или его представителям, включая, но не ограничиваясь этим, сообщения в электронных списках рассылки, системах контроля исходного кода и системах отслеживания проблем, которые управляются Лицензиаром или от его имени. Лицензиару с целью обсуждения и улучшения Работы, но исключая сообщение, которое явно помечено или иным образом обозначено в письменной форме владельцем авторских прав как &quot;Не является вкладом&quot;.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">&quot;Вкладчик&quot; означает Лицензиара и любое физическое или Юридическое лицо, от имени которого Лицензиар получил Вклад и впоследствии включил его в Произведение.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Предоставление лицензии на авторское право. В соответствии с условиями и положениями настоящей Лицензии, каждый Участник настоящим предоставляет Вам бессрочную, всемирную, неисключительную, бесплатную, безвозмездную, безотзывную лицензию на авторское право на воспроизведение, подготовку Производных Работ, публичную демонстрацию, публичное исполнение, сублицензирование и распространение Работы и таких Производных Работ в форме источника или объекта.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Выдача патентной лицензии. В соответствии с условиями и положениями настоящей Лицензии, каждый Участник настоящим предоставляет Вам бессрочную, всемирную, неисключительную, бесплатную, безвозмездную, безотзывную (за исключением случаев, указанных в этом разделе) патентную лицензию на создание, использование, предложение о продаже, продажу, импорт, и иным образом передавать Работу, если такая лицензия применяется только к тем патентным заявкам, лицензируемым таким Автором, которые обязательно нарушаются их Вкладом (вкладами) отдельно или в сочетании их Вклада (ов) с Работой, на которую был представлен такой Вклад (ы). Если Вы подаете патентный иск против какой-либо организации (включая перекрестный иск или встречный иск в судебном процессе), утверждая, что Работа или Вклад, включенный в Работу, представляют собой прямое или косвенное нарушение патентных прав, то любые патентные лицензии, предоставленные Вам в соответствии с этой Лицензией на эту Работу, прекращаются с даты начала такого судебного разбирательства. подшито.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Перераспределение. Вы можете воспроизводить и распространять копии Произведения или Производных от него Произведений на любом носителе, с изменениями или без изменений, а также в Исходной или Объектной форме, при условии, что Вы выполняете следующие условия:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">(а) Вы должны предоставить любым другим получателям Произведения или Производных произведений копию этой Лицензии; и</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">(b) Вы должны сделать так, чтобы на любых измененных файлах были заметные уведомления о том, что Вы изменили файлы; и</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">(c) Вы должны сохранять в Исходной форме любых Производных Работ, которые Вы распространяете, все уведомления об авторских правах, патентах, товарных знаках и атрибуции из Исходной формы Работы, за исключением тех уведомлений, которые не относятся к какой-либо части Производных Работ; и</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">(d) Если Произведение включает текстовый файл &quot;УВЕДОМЛЕНИЕ&quot; как часть его распространения, то любые Производные работы, которые Вы распространяете, должны включать читаемую копию уведомлений об атрибуции, содержащихся в таком файле УВЕДОМЛЕНИЙ, за исключением тех уведомлений, которые не относятся к какой-либо части Производных работ, по крайней мере, в одном из следующих мест: в текстовом файле УВЕДОМЛЕНИЯ, распространяемом как часть Производных работ; в исходной форме или документации, если они предоставляются вместе с Производными работами; или в пределах отображения, созданного Производными работами, если и где обычно появляются такие уведомления третьих лиц. Содержимое файла УВЕДОМЛЕНИЯ предназначено исключительно для информационных целей и не изменяет Лицензию. Вы можете добавлять Свои собственные уведомления об атрибуции в Производные Произведения, которые Вы распространяете, вместе с текстом УВЕДОМЛЕНИЯ из Произведения или в качестве дополнения к нему, при условии, что такие дополнительные уведомления об атрибуции не могут быть истолкованы как изменение Лицензии.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Вы можете добавить свое собственное заявление об авторских правах к Своим модификациям и можете предоставить дополнительные или другие лицензионные условия и положения для использования, воспроизведения или распространения Ваших модификаций или для любых таких Производных работ в целом, при условии, что Ваше использование, воспроизведение и распространение Работы иным образом соответствуют условиям, изложенным в этом Лицензия.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Представление взносов. Если Вы явно не укажете иное, любой Вклад, намеренно представленный Вами Лицензиару для включения в Произведение, подпадает под условия настоящей Лицензии, без каких-либо дополнительных условий или положений. Несмотря на вышесказанное, ничто в настоящем документе не заменяет или не изменяет условия любого отдельного лицензионного соглашения, которое вы, возможно, заключили с Лицензиаром в отношении таких Взносов.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Торговые марки. Настоящая Лицензия не дает разрешения на использование торговых наименований, товарных знаков, знаков обслуживания или названий продуктов Лицензиара, за исключением случаев, когда это требуется для разумного и обычного использования при описании происхождения Произведения и воспроизведении содержимого файла УВЕДОМЛЕНИЯ.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Отказ от гарантии. Если это не требуется применимым законодательством или не согласовано в письменной форме, Лицензиар предоставляет Работу (и каждый Участник предоставляет свои Материалы) на УСЛОВИЯХ &quot;КАК ЕСТЬ&quot;, БЕЗ КАКИХ-ЛИБО ГАРАНТИЙ ИЛИ УСЛОВИЙ, явных или подразумеваемых, включая, помимо прочего, любые гарантии или условия ПРАВА СОБСТВЕННОСТИ, НЕНАРУШЕНИЯ ПРАВ, ПРИГОДНОСТЬ ДЛЯ ПРОДАЖИ или ПРИГОДНОСТЬ ДЛЯ ОПРЕДЕЛЕННОЙ ЦЕЛИ. Вы несете единоличную ответственность за определение целесообразности использования или распространения Работы и принимаете на себя любые риски, связанные с использованием Вами разрешений в соответствии с настоящей Лицензией.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Ограничение ответственности. Ни в коем случае и ни в соответствии с какой правовой теорией, будь то в результате деликта (включая халатность), контракта или иным образом, за исключением случаев, предусмотренных применимым законодательством (например, преднамеренные и грубые небрежные действия) или согласованные в письменной форме, любой Вкладчик не несет ответственности перед Вами за ущерб, включая любые прямые, косвенные, специальные, случайный или косвенный ущерб любого характера, возникший в результате действия настоящей Лицензии или в результате использования или невозможности использования Произведения (включая, но не ограничиваясь ущербом в связи с потерей деловой репутации, остановкой работы, сбоем или неисправностью компьютера или любым другим коммерческим ущербом или убытками), даже если такой Вкладчик был предупрежден о возможности такого ущерба.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Принятие Гарантии или Дополнительной ответственности. Распространяя Произведение или Производные от него Произведения, Вы можете предложить и взимать плату за принятие поддержки, гарантии, возмещения убытков или других обязательств по ответственности и/или прав, соответствующих настоящей Лицензии. Однако, принимая такие обязательства, Вы можете действовать только от Своего имени и под Свою исключительную ответственность, а не от имени любого другого Участника, и только в том случае, если Вы согласны возместить, защитить и обезопасить каждого Участника от любой ответственности, понесенной таким Участником, или претензий, предъявленных к нему по причине вы принимаете любую такую гарантию или дополнительную ответственность.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">ОКОНЧАНИЕ ДЕЙСТВИЯ ПРАВИЛ И УСЛОВИЙ</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">ПРИЛОЖЕНИЕ: Как применить лицензию Apache к вашей работе.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Чтобы применить лицензию Apache к своей работе, приложите следующее</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">шаблонное уведомление с полями, заключенными в квадратные скобки &quot;[]&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">заменен вашей собственной идентификационной информацией. (Не включайте</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">скобки!) Текст должен быть заключен в соответствующий</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">синтаксис комментария для формата файла. Мы также рекомендуем, чтобы</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">название файла или класса и описание назначения были включены на той</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">же &quot;печатной странице&quot;, что и уведомление об авторских правах, для облегчения</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">идентификации в сторонних архивах.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Авторское право [2022] [Макеев Антон Николаевич]</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Лицензирован по лицензии Apache версии 2.0 (&quot;Лицензия&quot;); вы не можете использовать этот файл, кроме как в соответствии с Лицензией. Вы можете получить копию Лицензии по адресу</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">http://www.apache.org/licenses/LICENSE-2.0</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p></body></html>"))
        self.label_41.setText(_translate("MainWindow", "Руководство пользователя для модуля \"Сиситема управления базами данных\""))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:15pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">Данная система управления базами данных предназначена для добавления новых пользвоателей данной Системой. При добавлении нового пользователя необходимо указать:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">- имя;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">- фамилия;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">- должность;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">- email;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">- логин;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">- пароль;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">- уровень допуска.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">Необходимо отметить 7 пункт - уровень допуска. На выбор доступно две роли:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">1. Администратор - имеет доступ ко всем модулям Системы, может добавлять и удалять пользователей, а также изменять данные уже существущих пользователей Ссистемы;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">2. Пользователь - имеет ограничение на использование некоторыми модулями, не имеет права совершать операции с данными;</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">Система упарвления базами данных предлагает следующий функционал:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">1. Добавить - можно добавить новго пользвоателя;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">2. Данные -  на странице будут отражены все текущие пользователи Системы;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">3. Найти - найти конкретного пользователя в базе данных;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">4. Изменить - изменить данные пользователей Системы;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">5. Удалить - удалить пользваотеля из базы данных Системы.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; color:#ffffff;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; color:#ffffff;\"><br /></p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "Система управления базой данных"))
        self.label_6.setText(_translate("MainWindow", "имя"))
        self.label_7.setText(_translate("MainWindow", "фамилия"))
        self.label_8.setText(_translate("MainWindow", "должность"))
        self.label_9.setText(_translate("MainWindow", "email"))
        self.label_10.setText(_translate("MainWindow", "логин"))
        self.label_11.setText(_translate("MainWindow", "пароль"))
        self.label_12.setText(_translate("MainWindow", "уровень допуска"))
        self.cb_user_role.setItemText(0, _translate("MainWindow", "Пользователь"))
        self.cb_user_role.setItemText(1, _translate("MainWindow", "Администратор"))
        self.btn_add_new_user.setText(_translate("MainWindow", "Добавить пользователя"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_add_data), _translate("MainWindow", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_data), _translate("MainWindow", "Данные"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_search_page), _translate("MainWindow", "Найти"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_change_page), _translate("MainWindow", "Изменить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_delete_page), _translate("MainWindow", "Удалить"))
        self.label_38.setText(_translate("MainWindow", "Список баз данных"))
        self.label_29.setText(_translate("MainWindow", "Список доступных баз данных"))
        self.label_30.setText(_translate("MainWindow", "Список доступных таблиц"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
import icons_rc_2

