# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_directory/GUI/client_gui_for_test_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1223, 1025)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(45, 45, 45);\n"
"background-color: rgb(0, 0, 0);\n"
"background-color: rgb(24, 24, 36);\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(9, 5, 13)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(45, 45, 45);\n"
"background-color: rgb(9, 5, 13)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_minimize_window = QtWidgets.QPushButton(self.frame_4)
        self.btn_minimize_window.setStyleSheet("QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid  rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.btn_minimize_window.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize_window.setIcon(icon)
        self.btn_minimize_window.setIconSize(QtCore.QSize(25, 25))
        self.btn_minimize_window.setObjectName("btn_minimize_window")
        self.horizontalLayout_2.addWidget(self.btn_minimize_window)
        self.btn_restore_window = QtWidgets.QPushButton(self.frame_4)
        self.btn_restore_window.setStyleSheet("QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid  rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.btn_restore_window.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/maximize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_restore_window.setIcon(icon1)
        self.btn_restore_window.setIconSize(QtCore.QSize(25, 25))
        self.btn_restore_window.setObjectName("btn_restore_window")
        self.horizontalLayout_2.addWidget(self.btn_restore_window)
        self.btn_close_window = QtWidgets.QPushButton(self.frame_4)
        self.btn_close_window.setStyleSheet("QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid  rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.btn_close_window.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/x-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close_window.setIcon(icon2)
        self.btn_close_window.setIconSize(QtCore.QSize(25, 25))
        self.btn_close_window.setObjectName("btn_close_window")
        self.horizontalLayout_2.addWidget(self.btn_close_window)
        self.horizontalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.authorization_page = QtWidgets.QWidget()
        self.authorization_page.setObjectName("authorization_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.authorization_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.authorization_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_30.setSpacing(20)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 40))
        self.label_2.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_30.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.le_login = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_login.sizePolicy().hasHeightForWidth())
        self.le_login.setSizePolicy(sizePolicy)
        self.le_login.setMinimumSize(QtCore.QSize(0, 40))
        self.le_login.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.le_login.setFont(font)
        self.le_login.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_login.setObjectName("le_login")
        self.verticalLayout_30.addWidget(self.le_login)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_30.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.le_password = QtWidgets.QLineEdit(self.frame_5)
        self.le_password.setMinimumSize(QtCore.QSize(0, 40))
        self.le_password.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.le_password.setFont(font)
        self.le_password.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_password.setObjectName("le_password")
        self.verticalLayout_30.addWidget(self.le_password)
        self.btn_login = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_login.sizePolicy().hasHeightForWidth())
        self.btn_login.setSizePolicy(sizePolicy)
        self.btn_login.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_login.setMaximumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid rgb(24, 24, 36);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_login.setFlat(False)
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout_30.addWidget(self.btn_login)
        self.btn_registrarion = QtWidgets.QPushButton(self.frame_5)
        self.btn_registrarion.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_registrarion.setMaximumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_registrarion.setFont(font)
        self.btn_registrarion.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid rgb(24, 24, 36);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_registrarion.setObjectName("btn_registrarion")
        self.verticalLayout_30.addWidget(self.btn_registrarion)
        self.verticalLayout_3.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.authorization_page)
        self.two_factor_authentication_page = QtWidgets.QWidget()
        self.two_factor_authentication_page.setObjectName("two_factor_authentication_page")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.two_factor_authentication_page)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.frame_33 = QtWidgets.QFrame(self.two_factor_authentication_page)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_44.setContentsMargins(20, 20, -1, 20)
        self.verticalLayout_44.setSpacing(20)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.label_21 = QtWidgets.QLabel(self.frame_33)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_44.addWidget(self.label_21)
        self.le_email_code = QtWidgets.QLineEdit(self.frame_33)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.le_email_code.setFont(font)
        self.le_email_code.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_email_code.setObjectName("le_email_code")
        self.verticalLayout_44.addWidget(self.le_email_code)
        self.btn_accept_code = QtWidgets.QPushButton(self.frame_33)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_accept_code.setFont(font)
        self.btn_accept_code.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid rgb(24, 24, 36);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_accept_code.setObjectName("btn_accept_code")
        self.verticalLayout_44.addWidget(self.btn_accept_code)
        self.btn_open_authorization_page = QtWidgets.QPushButton(self.frame_33)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_authorization_page.setFont(font)
        self.btn_open_authorization_page.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid rgb(24, 24, 36);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_open_authorization_page.setObjectName("btn_open_authorization_page")
        self.verticalLayout_44.addWidget(self.btn_open_authorization_page)
        self.verticalLayout_43.addWidget(self.frame_33, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.two_factor_authentication_page)
        self.main_container_page = QtWidgets.QWidget()
        self.main_container_page.setObjectName("main_container_page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.main_container_page)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.menu_container = QtWidgets.QFrame(self.main_container_page)
        self.menu_container.setMaximumSize(QtCore.QSize(300, 16777215))
        self.menu_container.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.menu_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_container.setObjectName("menu_container")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.menu_container)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.menu_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toolBox = QtWidgets.QToolBox(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.toolBox.setObjectName("toolBox")
        self.page_server_menu = QtWidgets.QWidget()
        self.page_server_menu.setGeometry(QtCore.QRect(0, 0, 258, 708))
        self.page_server_menu.setObjectName("page_server_menu")
        self.splitter_2 = QtWidgets.QSplitter(self.page_server_menu)
        self.splitter_2.setGeometry(QtCore.QRect(10, 120, 231, 261))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.btn_server_manual = QtWidgets.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_server_manual.setFont(font)
        self.btn_server_manual.setStyleSheet("QPushButton {\n"
"    border: 5px groove rgb(30, 30, 30);\n"
"    border-left-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid  rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.btn_server_manual.setObjectName("btn_server_manual")
        self.btn_show_server_page = QtWidgets.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_show_server_page.setFont(font)
        self.btn_show_server_page.setStyleSheet("QPushButton {\n"
"    border: 5px groove rgb(30, 30, 30);\n"
"    border-left-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid  rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.btn_show_server_page.setObjectName("btn_show_server_page")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/server.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_server_menu, icon3, "")
        self.page_dbms_menu = QtWidgets.QWidget()
        self.page_dbms_menu.setGeometry(QtCore.QRect(0, 0, 258, 708))
        self.page_dbms_menu.setObjectName("page_dbms_menu")
        self.splitter_3 = QtWidgets.QSplitter(self.page_dbms_menu)
        self.splitter_3.setGeometry(QtCore.QRect(10, 120, 231, 261))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.btn_show_database = QtWidgets.QPushButton(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_show_database.setFont(font)
        self.btn_show_database.setStyleSheet("QPushButton {\n"
"    border: 5px groove rgb(30, 30, 30);\n"
"    border-left-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid  rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.btn_show_database.setObjectName("btn_show_database")
        self.btn_dbms_manual = QtWidgets.QPushButton(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dbms_manual.setFont(font)
        self.btn_dbms_manual.setStyleSheet("QPushButton {\n"
"    border: 5px groove rgb(30, 30, 30);\n"
"    border-left-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid  rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.btn_dbms_manual.setObjectName("btn_dbms_manual")
        self.btn_open_list_of_db = QtWidgets.QPushButton(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_list_of_db.setFont(font)
        self.btn_open_list_of_db.setStyleSheet("QPushButton {\n"
"    border: 5px groove rgb(30, 30, 30);\n"
"    border-left-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid  rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.btn_open_list_of_db.setObjectName("btn_open_list_of_db")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/archive.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_dbms_menu, icon4, "")
        self.horizontalLayout_6.addWidget(self.toolBox)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.menu_container)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_main_page_manual = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_main_page_manual.setFont(font)
        self.btn_main_page_manual.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid rgb(24, 24, 36);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_main_page_manual.setIcon(icon5)
        self.btn_main_page_manual.setObjectName("btn_main_page_manual")
        self.verticalLayout_5.addWidget(self.btn_main_page_manual)
        self.btn_open_authorization_page_2 = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_authorization_page_2.setFont(font)
        self.btn_open_authorization_page_2.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid rgb(24, 24, 36);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/log-in.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_open_authorization_page_2.setIcon(icon6)
        self.btn_open_authorization_page_2.setObjectName("btn_open_authorization_page_2")
        self.verticalLayout_5.addWidget(self.btn_open_authorization_page_2)
        self.btn_exit = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 5px solid rgb(24, 24, 36);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(24, 24, 36);\n"
"    border: 5px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_exit.setIcon(icon2)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout_5.addWidget(self.btn_exit)
        self.verticalLayout_4.addWidget(self.frame_9, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_5.addWidget(self.menu_container)
        self.frame_7 = QtWidgets.QFrame(self.main_container_page)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stackedWidget_main = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget_main.setObjectName("stackedWidget_main")
        self.page_about_system = QtWidgets.QWidget()
        self.page_about_system.setObjectName("page_about_system")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_about_system)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_6 = QtWidgets.QFrame(self.page_about_system)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.verticalLayout_7.addWidget(self.frame_6, 0, QtCore.Qt.AlignTop)
        self.frame_10 = QtWidgets.QFrame(self.page_about_system)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.textEdit = QtWidgets.QTextEdit(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_9.addWidget(self.textEdit)
        self.verticalLayout_7.addWidget(self.frame_10)
        self.stackedWidget_main.addWidget(self.page_about_system)
        self.page_server_manual = QtWidgets.QWidget()
        self.page_server_manual.setObjectName("page_server_manual")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout(self.page_server_manual)
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.frame_35 = QtWidgets.QFrame(self.page_server_manual)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.textEdit_5 = QtWidgets.QTextEdit(self.frame_35)
        self.textEdit_5.setObjectName("textEdit_5")
        self.verticalLayout_49.addWidget(self.textEdit_5)
        self.verticalLayout_48.addWidget(self.frame_35)
        self.stackedWidget_main.addWidget(self.page_server_manual)
        self.page_client = QtWidgets.QWidget()
        self.page_client.setObjectName("page_client")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.page_client)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_21 = QtWidgets.QFrame(self.page_client)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.lw_incoming_msg_from_server = QtWidgets.QListWidget(self.frame_21)
        self.lw_incoming_msg_from_server.setObjectName("lw_incoming_msg_from_server")
        self.verticalLayout_24.addWidget(self.lw_incoming_msg_from_server)
        self.verticalLayout_23.addWidget(self.frame_21)
        self.stackedWidget_main.addWidget(self.page_client)
        self.page_dbms_manual = QtWidgets.QWidget()
        self.page_dbms_manual.setObjectName("page_dbms_manual")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.page_dbms_manual)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_22 = QtWidgets.QFrame(self.page_dbms_manual)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.textEdit_4 = QtWidgets.QTextEdit(self.frame_22)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setStyleSheet("")
        self.textEdit_4.setReadOnly(True)
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout_47.addWidget(self.textEdit_4)
        self.verticalLayout_26.addWidget(self.frame_22)
        self.stackedWidget_main.addWidget(self.page_dbms_manual)
        self.page_show_dbms = QtWidgets.QWidget()
        self.page_show_dbms.setObjectName("page_show_dbms")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.page_show_dbms)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.tabWidget = QtWidgets.QTabWidget(self.page_show_dbms)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_add_data = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tab_add_data.setFont(font)
        self.tab_add_data.setObjectName("tab_add_data")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.tab_add_data)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 0, -1, -1)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.tab_add_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.le_name = QtWidgets.QLineEdit(self.tab_add_data)
        self.le_name.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.le_name.setFont(font)
        self.le_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_name.setObjectName("le_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_name)
        self.label_7 = QtWidgets.QLabel(self.tab_add_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.le_soname = QtWidgets.QLineEdit(self.tab_add_data)
        self.le_soname.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.le_soname.setFont(font)
        self.le_soname.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_soname.setObjectName("le_soname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_soname)
        self.label_8 = QtWidgets.QLabel(self.tab_add_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.le_rank = QtWidgets.QLineEdit(self.tab_add_data)
        self.le_rank.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.le_rank.setFont(font)
        self.le_rank.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_rank.setObjectName("le_rank")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_rank)
        self.label_9 = QtWidgets.QLabel(self.tab_add_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.le_email = QtWidgets.QLineEdit(self.tab_add_data)
        self.le_email.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.le_email.setFont(font)
        self.le_email.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_email.setObjectName("le_email")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_email)
        self.label_10 = QtWidgets.QLabel(self.tab_add_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.le_login_2 = QtWidgets.QLineEdit(self.tab_add_data)
        self.le_login_2.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.le_login_2.setFont(font)
        self.le_login_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_login_2.setObjectName("le_login_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.le_login_2)
        self.label_11 = QtWidgets.QLabel(self.tab_add_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.le_password_2 = QtWidgets.QLineEdit(self.tab_add_data)
        self.le_password_2.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.le_password_2.setFont(font)
        self.le_password_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_password_2.setObjectName("le_password_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.le_password_2)
        self.label_12 = QtWidgets.QLabel(self.tab_add_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.btn_add_new_user = QtWidgets.QPushButton(self.tab_add_data)
        self.btn_add_new_user.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add_new_user.setFont(font)
        self.btn_add_new_user.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 5px solid;\n"
"border-bottom-color: rgb(255, 255, 255);")
        self.btn_add_new_user.setObjectName("btn_add_new_user")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.btn_add_new_user)
        self.cb_user_role = QtWidgets.QComboBox(self.tab_add_data)
        self.cb_user_role.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.cb_user_role.setFont(font)
        self.cb_user_role.setStyleSheet("color: rgb(255, 255, 255);")
        self.cb_user_role.setObjectName("cb_user_role")
        self.cb_user_role.addItem("")
        self.cb_user_role.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cb_user_role)
        self.verticalLayout_29.addLayout(self.formLayout)
        self.tabWidget.addTab(self.tab_add_data, "")
        self.tab_data = QtWidgets.QWidget()
        self.tab_data.setObjectName("tab_data")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.tab_data)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.data_table_view = QtWidgets.QTableView(self.tab_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.data_table_view.setFont(font)
        self.data_table_view.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.data_table_view.setObjectName("data_table_view")
        self.verticalLayout_42.addWidget(self.data_table_view)
        self.tabWidget.addTab(self.tab_data, "")
        self.tab_search_page = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tab_search_page.setFont(font)
        self.tab_search_page.setObjectName("tab_search_page")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.tab_search_page)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.le_search_data_in_db = QtWidgets.QLineEdit(self.tab_search_page)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.le_search_data_in_db.setFont(font)
        self.le_search_data_in_db.setStyleSheet("color: rgb(255, 255, 255);")
        self.le_search_data_in_db.setObjectName("le_search_data_in_db")
        self.verticalLayout_27.addWidget(self.le_search_data_in_db)
        self.search_table_view = QtWidgets.QTableView(self.tab_search_page)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.search_table_view.setFont(font)
        self.search_table_view.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.search_table_view.setObjectName("search_table_view")
        self.verticalLayout_27.addWidget(self.search_table_view)
        self.tabWidget.addTab(self.tab_search_page, "")
        self.tab_change_page = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tab_change_page.setFont(font)
        self.tab_change_page.setObjectName("tab_change_page")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.tab_change_page)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.change_table_view = QtWidgets.QTableView(self.tab_change_page)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.change_table_view.setFont(font)
        self.change_table_view.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.change_table_view.setObjectName("change_table_view")
        self.verticalLayout_28.addWidget(self.change_table_view)
        self.tabWidget.addTab(self.tab_change_page, "")
        self.tab_delete_page = QtWidgets.QWidget()
        self.tab_delete_page.setObjectName("tab_delete_page")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.tab_delete_page)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.delete_table_view = QtWidgets.QTableView(self.tab_delete_page)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.delete_table_view.setFont(font)
        self.delete_table_view.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delete_table_view.setObjectName("delete_table_view")
        self.verticalLayout_31.addWidget(self.delete_table_view)
        self.tabWidget.addTab(self.tab_delete_page, "")
        self.verticalLayout_25.addWidget(self.tabWidget)
        self.stackedWidget_main.addWidget(self.page_show_dbms)
        self.page_list_of_db = QtWidgets.QWidget()
        self.page_list_of_db.setObjectName("page_list_of_db")
        self.verticalLayout_52 = QtWidgets.QVBoxLayout(self.page_list_of_db)
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.frame_37 = QtWidgets.QFrame(self.page_list_of_db)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_37.sizePolicy().hasHeightForWidth())
        self.frame_37.setSizePolicy(sizePolicy)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.verticalLayout_53 = QtWidgets.QVBoxLayout(self.frame_37)
        self.verticalLayout_53.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.frame_38 = QtWidgets.QFrame(self.frame_37)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_38.sizePolicy().hasHeightForWidth())
        self.frame_38.setSizePolicy(sizePolicy)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_38)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_40 = QtWidgets.QFrame(self.frame_38)
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.verticalLayout_56 = QtWidgets.QVBoxLayout(self.frame_40)
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.label_29 = QtWidgets.QLabel(self.frame_40)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_29.setObjectName("label_29")
        self.verticalLayout_56.addWidget(self.label_29)
        self.lw_db_widget = QtWidgets.QListWidget(self.frame_40)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lw_db_widget.setFont(font)
        self.lw_db_widget.setStyleSheet("color: rgb(255, 255, 255);")
        self.lw_db_widget.setObjectName("lw_db_widget")
        self.verticalLayout_56.addWidget(self.lw_db_widget)
        self.horizontalLayout_11.addWidget(self.frame_40)
        self.frame_41 = QtWidgets.QFrame(self.frame_38)
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.verticalLayout_55 = QtWidgets.QVBoxLayout(self.frame_41)
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.label_30 = QtWidgets.QLabel(self.frame_41)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_30.setObjectName("label_30")
        self.verticalLayout_55.addWidget(self.label_30)
        self.lw_table_widget = QtWidgets.QListWidget(self.frame_41)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lw_table_widget.setFont(font)
        self.lw_table_widget.setStyleSheet("color: rgb(255, 255, 255);")
        self.lw_table_widget.setObjectName("lw_table_widget")
        self.verticalLayout_55.addWidget(self.lw_table_widget)
        self.horizontalLayout_11.addWidget(self.frame_41)
        self.verticalLayout_53.addWidget(self.frame_38, 0, QtCore.Qt.AlignTop)
        self.frame_39 = QtWidgets.QFrame(self.frame_37)
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_54 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.tv_for_db_view = QtWidgets.QTableView(self.frame_39)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tv_for_db_view.setFont(font)
        self.tv_for_db_view.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tv_for_db_view.setObjectName("tv_for_db_view")
        self.verticalLayout_54.addWidget(self.tv_for_db_view)
        self.verticalLayout_53.addWidget(self.frame_39)
        self.verticalLayout_52.addWidget(self.frame_37)
        self.stackedWidget_main.addWidget(self.page_list_of_db)
        self.verticalLayout_6.addWidget(self.stackedWidget_main)
        self.horizontalLayout_5.addWidget(self.frame_7)
        self.stackedWidget.addWidget(self.main_container_page)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.toolBox.setCurrentIndex(0)
        self.stackedWidget_main.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ДЛЯ КЛИЕНТА"))
        self.label_2.setText(_translate("MainWindow", "ЛОГИН"))
        self.label_3.setText(_translate("MainWindow", "ПАРОЛЬ"))
        self.btn_login.setText(_translate("MainWindow", "Войти"))
        self.btn_registrarion.setText(_translate("MainWindow", "Добавить нового пользователя"))
        self.label_21.setText(_translate("MainWindow", "Код подтверждения"))
        self.btn_accept_code.setText(_translate("MainWindow", "Подтвердить"))
        self.btn_open_authorization_page.setText(_translate("MainWindow", "Страница авторизации"))
        self.btn_server_manual.setText(_translate("MainWindow", "Мануал"))
        self.btn_show_server_page.setText(_translate("MainWindow", "Старница клиента"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_server_menu), _translate("MainWindow", "Сервер"))
        self.btn_show_database.setText(_translate("MainWindow", "Открыть СУБД"))
        self.btn_dbms_manual.setText(_translate("MainWindow", "Мануал"))
        self.btn_open_list_of_db.setText(_translate("MainWindow", "Список баз данных"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_dbms_menu), _translate("MainWindow", "СУБД"))
        self.btn_main_page_manual.setText(_translate("MainWindow", "Главная страница"))
        self.btn_open_authorization_page_2.setText(_translate("MainWindow", "Страница авторизации"))
        self.btn_exit.setText(_translate("MainWindow", "Выход"))
        self.label_4.setText(_translate("MainWindow", "Информация о системе"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Программное обеспечение (далее ПО) – это комплекс из отдельных программ, которые объединены друг с другом для достижения общего результата. Современное ПО делится на модули, которые объединены в единую систему и дополняют друг друга. Модули взаимодействую друг с другом через запрограммированный алгоритм. ПО принято разделять на три группы: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">1.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Системное; </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">2.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Прикладное; </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">3.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Инструментальное. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">ПО, которое разрабатывается для защиты баз данных относится к системному. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Цель проекта. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Цель проекта - разработать систему обеспечения информационной безопасности баз данных (далее Система). В Системе должна быть предусмотрена защита базы данных от НСД. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Описание системы. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Система состоит из модулей, которые делятся на: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">1.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Защита системы; </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">2.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Система управления базами данных; </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">3.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Сервер; </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">4.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Журнал действий. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Первый модуль – защита системы. В данном модуле предоставляет следующие компоненты: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">1.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Идентификация и аутентификация. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Данный компонент предоставляет функционал для входа в Систему. Компонент содержит: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">― аутентификацию. Должностное лицо, должно пройти авторизацию при помощи ввода логина и пароля; </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">― идентификацию. Система сверяется с введёнными данными. Если введённые данные верны, то должностное лицо должно подтвердить вход по e-mail адресу. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">2.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Сканер портов. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Данный компонент предоставляет функционал для поиска открытых портов IP-адреса, на котором располагается сервер. Сканирование портов может помочь определить потенциальные цели атаки. Также позволяет выявить открытые и закрытые порты, порты, используемые операционной системой. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">3.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Отслеживание процессов. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Данный модуль позволяет отслеживать активные процессы операционной системы. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">4.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Сканирование системы. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Позволяет проверить файлы каталога на наличие вредоносного файла или программного обеспечения. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">5.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Блокировка внешних usb-носителей. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Данный модуль блокирует использование внешних usb-носителей. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">6.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Информация о системе. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Данный модуль позволяет получить более точную информацию об операционной системе, на которой установлена Система. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Второй модуль – Система управления базой данных. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Данный модуль предоставляет компоненты для управления базой данных. При помощи компонентов данного модуля данные в базе данных можно: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">1.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Добавлять; </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">2.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Изменять; </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">3.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Обновлять </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">4.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Удалять. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Третий модуль – Сервер. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Данный модуль предоставляет функционал при помощи которого пользователи могут безопасно подключиться по SSL-протоколу и получить свои данные, а также взаимодействовать с ними. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Четвёртый модуль – Журнал действий. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Данный модуль создаёт файлы для каждого модуля. В файлы записываются все действия пользователя совершённые им в Системе. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Отдельный модуль – Клиент. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Программное обеспечение, которое необходимо клиенту для получения своих данных из базы данных. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Система предусматривает три типа пользователей: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">1.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">Администратор – должностное лицо, которые выполняет функции администрирования базы данных и операционной системы сервера; </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">2.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\"> Пользователь –  пользователь, которому необходимо подключиться и получить свои персональные данные. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Доступ в Систему. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">При запуске Системы администратору необходимо пройти аутентификацию и идентификацию. При первом запуске необходимо пройти процедуру добавления нового пользователя. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Для добавления нового пользователя, Системе необходимо ввести следующие данные: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">1.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">имя; </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">2.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">фамилия; </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">3.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">адрес электронной почты (e-mail); </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">4.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">логин; </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">5.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">пароль; </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">6.</span><span style=\" font-family:\'Times New Roman\'; color:#ffffff;\">  </span><span style=\" color:#ffffff;\">роль (0 – администратор). </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">В дальнейшем адрес электронной почты будет использоваться для прохождения двухфакторной аутентификации. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Аутентификация в Системе осуществляется при помощи логина, пароля и специального кода, Если логин и пароль прошли проверку, то откроется страница для ввода кода. который приходит на адрес электронной почты. </span></p></body></html>"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Клиент предназначен для удалённого подключения пользователя. Пользователь может запросить информацию из базы данных. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Технология Клиент - Сервер реализована при помощи TCP/IP - протокола и защищённого SSL подключения.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">В настройках сервера можно задать IP-адрес и порт сервера, а также количество одновременных подключений к серверу.</span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:15pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">Данная система управления базами данных предназначена для добавления новых пользвоателей данной Системой. При добавлении нового пользователя необходимо указать:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">1. имя;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">2. фамилия;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">3. звание;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">4. email;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">5. логин;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">6. пароль;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">7. уровень допуска.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">Необходимо отметить 7 пункт - уровень допуска. На выбор доступно две роли:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">1. Администратор - имеет доступ ко всем модулям Системы, может добавлять и удалять пользователей, а также изменять данные уже существущих пользователей Ссистемы;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">2. Пользователь - имеет ограничение на использование некоторыми модулями, не имеет права совершать операции с данными;</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">Система упарвления базами данных предлагает следующий функционал:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">1. Добавить - можно добавить новго пользвоателя;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">2. Данные -  на странице будут отражены все текущие пользователи Системы;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">3. Найти - найти конкретного пользователя в базе данных;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">4. Изменить - изменить данные пользователей Системы;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">5. Удалить - удалить пользваотеля из базы данных Системы.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; color:#ffffff;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; color:#ffffff;\"><br /></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "имя"))
        self.label_7.setText(_translate("MainWindow", "фамилия"))
        self.label_8.setText(_translate("MainWindow", "звание"))
        self.label_9.setText(_translate("MainWindow", "email"))
        self.label_10.setText(_translate("MainWindow", "логин"))
        self.label_11.setText(_translate("MainWindow", "пароль"))
        self.label_12.setText(_translate("MainWindow", "уровень допуска"))
        self.btn_add_new_user.setText(_translate("MainWindow", "Добавить пользователя"))
        self.cb_user_role.setItemText(0, _translate("MainWindow", "Пользователь"))
        self.cb_user_role.setItemText(1, _translate("MainWindow", "Администратор"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_add_data), _translate("MainWindow", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_data), _translate("MainWindow", "Данные"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_search_page), _translate("MainWindow", "Найти"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_change_page), _translate("MainWindow", "Изменить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_delete_page), _translate("MainWindow", "Удалить"))
        self.label_29.setText(_translate("MainWindow", "Список доступных баз данных"))
        self.label_30.setText(_translate("MainWindow", "Список доступных таблиц"))
import icons_rc
